[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  framework = "vite"
  targetPort = 3000

[functions]
  directory = "netlify/functions"
